# Streamlit Cloud Secrets Configuration
# This file should be placed in .streamlit/secrets.toml
# AND it should be added to .gitignore

# Runtime flag
RUN_TIME = "cloud"  # use "cloud" / "local"in the Streamlit Cloud secret 
